### ISSUE TITLE
Move to nix-community?

### ISSUE THREAD

**Issue by Mic92** [nix-community/napalm#34]
https://old.reddit.com/r/NixOS/comments/ogy8vf/niv_naersk_napalm_moving_on/

You could simply transfer it to nix-community, we would assign you as a maintainer
but you could also add more people to the project as you wish.

**Comment by nmattia** [comment]
Done! https://github.com/nix-community/napalm

**Comment by Mic92** [comment]
I marked you as a maintainer. If you want to add more maintainers we can create a team in nix-community with access to the repo.

**Comment by nmattia** [comment]
Thanks @Mic92 ! Yes, let's do that. Is there someone in the community with good JS/npm knowledge?

**Comment by Mic92** [comment]
Mhm. Not so sure. Maybe I ask around in the community.

**Comment by jtojnar** [comment]
I use napalm and am somewhat familiar with the code base but can only offer being co-maintainer. For example, I would fix compatibility with new npm versions or more serious issues and review PRs but cannot really spend much time on general development.

**Comment by Mic92** [comment]
I created a napalm team where I invited @nmattia and @jtojnar

**Comment by nmattia** [comment]
@jtojnar I doubt there'll be much development needed; most likely just fixing up compatibility issues. I'm giving you write access. Thanks!

**Comment by Mic92** [comment]
@jtojnar already has case: https://github.com/orgs/nix-community/teams/napalm/members
