### ISSUE TITLE
Nix flake check is failing

### ISSUE THREAD

**Issue by Mazurel** [nix-community/napalm#36]
This repo provides a basic `flake.nix` file, but it looks like it is not working correctly when it comes to `nix flake check`. Running it like `nix flake check "github:nix-community/napalm" --no-write-lock-file` results in error: 
```
error: a 'aarch64-linux' with features {} is required to build '/nix/store/qmkfj51wpz34yrwl4zhavl7q02gvcmql-cabal2nix-napalm-registry.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, kvm, nixos-test}
```

From my tests, it looks like this error does not occur only when supported systems is only `x86_64-linux`. This issue can be easily fixed by supporting only this system, although I do not know how the maintainers would see this solution. I would also suggest using pinned `nixpkgs` as flake inputs so that the flake would be "safer" aka using `flake.lock`.

In case the solution that I suggested is acceptable, I can make PR with proper changes.

**Comment by phanirithvij** [comment]
Can be closed
